### ISSUE TITLE
modules/terraform/var-file.go:142:8: undefined: hcl.Decode

### ISSUE THREAD

**Issue by WafflesMcDuff** [gruntwork-io/terratest#784] opened 2021-02-15 17:55 UTC
Latest release is causing an error:
```
vendor/github.com/gruntwork-io/terratest/modules/terraform/var-file.go:142:8: undefined: hcl.Decode
FAIL	git.*******.com/mongodbatlas-tf/terratest/mongodbatlas-cluster [build failed]
FAIL

Exited with code exit status 2
```

https://github.com/gruntwork-io/terratest/blob/88ba3f070a939aca8351eae616a3c899bfe28b91/modules/terraform/var-file.go#L142

**Comment by WafflesMcDuff** [comment] 2021-02-15 18:06
@brikis98
@alpacamybags118

**Comment by WafflesMcDuff** [comment] 2021-02-15 18:19
Problem started with #733

**Comment by WafflesMcDuff** [comment] 2021-02-15 18:45
Apparently this version breaks compatibility with go dep.
Had to switch from
`dep init && dep ensure -vendor-only `
to
`go mod init git.rockfin.com/mongodbtatlas-tf && go mod vendor`

**Comment by alpacamybags118** [comment] 2021-02-15 18:49
I think the root of the issue is dep is trying to pull v2 of hcl while the go mod of the terratest library explicitly referenes v1, so dep isnt respecting the libraries required version

**Comment by bgarcial** [comment] 2021-02-16 10:34
@alpacamybags118, @WafflesMcDuff I got the same error when running `go get -u github.com/gruntwork-io/terratest/modules/terraform` in our pipeline. I was wondering how can I use the [previous release](https://github.com/gruntwork-io/terratest/releases/tag/v0.32.5)in the meantime. I will appreciate your piece of advise.

**Comment by avishnyakov** [comment] 2021-02-17 21:36
Confirming, having same problem with the recent changes. Testing, trying to find a workaround.

**Comment by getSurreal** [comment] 2021-02-17 21:40
As WafflesMcDuff mentioned, use

`go mod init`

instead of

`dep init`

**Comment by yorinasub17** [comment] 2021-02-18 17:30
This is indeed a bug as we should be using hclv2. Will work on updating the library function to use hcl v2 asap.

**Comment by jnovick** [comment] 2021-02-23 15:09
This issue is affecting me as well. Part of the pipeline we wrote ensures we always use the latest terratest version so it has been broken and preventing any tests from actually running.

**Comment by yorinasub17** [comment] 2021-02-23 19:08
Potential fix for this was released https://github.com/gruntwork-io/terratest/releases/tag/v0.32.8

Please try it out and see if it resolves this.

**Comment by jnovick** [comment] 2021-02-23 20:36
Unfortunately I am still having this issue. I assume that is why you re-opened the issue, but wanted to comment in case you were unaware.

**Comment by yorinasub17** [comment] 2021-02-23 20:41
Can you share with me the error message you got? It should be different since the call to `hcl.Decode` is no longer in the source code.

If you are still getting the same error message, then you need to bump terratest in your `go.mod`.

**Comment by jnovick** [comment] 2021-02-24 18:10
It is different now. Is this a separate issue or still the same issue?

```
package command-line-arguments (test)
	imports github.com/gruntwork-io/terratest/modules/terraform
	imports github.com/hashicorp/hcl/v2/hclparse: cannot find package "github.com/hashicorp/hcl/v2/hclparse" in any of:
	/usr/vsts/pipeline-agent1/_work/_tool/go/1.13.5/x64/src/github.com/hashicorp/hcl/v2/hclparse (from $GOROOT)
	/home/Azureuser/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOPATH)
```

**Comment by yorinasub17** [comment] 2021-02-24 19:00
Ah yes this is a separate issue. Can you try running `go mod tidy` to see if that resolves your issue?

**Comment by jnovick** [comment] 2021-02-26 18:38
I was able to fix my new issue with `GO111MODULE=on` as per https://github.com/hashicorp/hcl/issues/371 so your update to terratest resolved my problems. Thank you.

**Comment by yorinasub17** [comment] 2021-02-26 19:46
Thanks for confirming! Will close this issue then. Please open a new issue if you run into other issues with go dependencies!

**Closed by yorinasub17** 2021-02-26 19:46 UTC
Labels: bug
