### ISSUE TITLE
tunnel.go from k8s package seems to be broken

### ISSUE THREAD

**Issue by pardhu-pokuri** [gruntwork-io/terratest#346] opened 2019-08-01 12:40 UTC
One of the imports from **"https://github.com/gruntwork-io/terratest/blob/master/modules/k8s/tunnel.go"** is **"k8s.io/kubernetes/pkg/kubectl/generate".** But the "generate" package seems to be moved to staging by kubernetes folks and this dependent package is not coming while building terratest code in our project. This has broken the terratest. Can you provide any solution for this?

**Comment by yorinasub17** [comment] 2019-08-01 14:41
I am looking into this now. Can you try switching the terratest reference in your dep `Gopkg.toml` to `branch = "yori-fix-more-dep-issues"` and see if that works for you?

**Comment by scrumteamravens** [comment] 2019-08-02 09:53
Hi Yori,

We are facing below issue after using your branch - 
[[constraint]]
  branch = "yori-fix-more-dep-issues"
  name = "github.com/gruntwork-io/terratest"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-9.0"
  name = "k8s.io/client-go"

--------------------

	region-override: Could not introduce github.com/gruntwork-io/terratest@region-override, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	rileykarson-gcp-oslogin: Could not introduce github.com/gruntwork-io/terratest@rileykarson-gcp-oslogin, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	terraform12: Could not introduce github.com/gruntwork-io/terratest@terraform12, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	upgrade12: Could not introduce github.com/gruntwork-io/terratest@upgrade12, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	use-my-ssh-keys: Could not introduce github.com/gruntwork-io/terratest@use-my-ssh-keys, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	yori-fix-more-dep-issues: Could not introduce github.com/gruntwork-io/terratest@yori-fix-more-dep-issues, as it has a dependency on k8s.io/api with constraint a33c8200050fc0751848276811abf3fc029b3133, which has no overlap with existing constraint release-1.12 from (root)
	yori-temp: Could not introduce github.com/gruntwork-io/terratest@yori-temp, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	yori-temp-2: Could not introduce github.com/gruntwork-io/terratest@yori-temp-2, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	yori-temp-72: Could not introduce github.com/gruntwork-io/terratest@yori-temp-72, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
	yori-temp-75: Could not introduce github.com/gruntwork-io/terratest@yori-temp-75, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.

**Comment by yorinasub17** [comment] 2019-08-02 14:13
If you look at the error log, you will see:

```
yori-fix-more-dep-issues: Could not introduce github.com/gruntwork-io/terratest@yori-fix-more-dep-issues, as it has a dependency on k8s.io/api with constraint a33c8200050fc0751848276811abf3fc029b3133, which has no overlap with existing constraint release-1.12 from (root)
```

This is saying that the specific version of `k8s.io/api` specified by `terratest` is incompatible with the constraints your project is setting (which is to use branch `release-1.12`). You need to remove all the other k8s related constraints you have in your `Gopkg.toml`. Those are all pulled in as transitive rules from `terratest`.

**Comment by yorinasub17** [comment] 2019-08-02 17:57
FYI https://github.com/gruntwork-io/terratest/releases/tag/v0.18.2 has been released with the changes in `yori-fix-more-dep-issues`.

I'll keep this open until I have confirmation from either of you that the new version has resolved your issues!

**Comment by scrumteamravens** [comment] 2019-08-05 11:40
Tried as per your suggestion but still facing below issues, Now i kept only teratest in the .toml file
[[constraint]]

branch = "yori-fix-more-dep-issues"
name = "github.com/gruntwork-io/terratest"


pull-request-340: Could not introduce github.com/gruntwork-io/terratest@pull-request-340, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        pull-request-343: Could not introduce github.com/gruntwork-io/terratest@pull-request-343, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        pull-request-344: Could not introduce github.com/gruntwork-io/terratest@pull-request-344, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        region-override: Could not introduce github.com/gruntwork-io/terratest@region-override, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        rileykarson-gcp-oslogin: Could not introduce github.com/gruntwork-io/terratest@rileykarson-gcp-oslogin, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        terraform12: Could not introduce github.com/gruntwork-io/terratest@terraform12, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        upgrade12: Could not introduce github.com/gruntwork-io/terratest@upgrade12, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        use-my-ssh-keys: Could not introduce github.com/gruntwork-io/terratest@use-my-ssh-keys, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        yori-fix-more-dep-issues: Could not introduce github.com/gruntwork-io/terratest@yori-fix-more-dep-issues, as it has a dependency on k8s.io/api with constraint a33c8200050fc0751848276811abf3fc029b3133, which does not allow the currently selected version of kubernetes-1.9.9-beta.0
        yori-temp: Could not introduce github.com/gruntwork-io/terratest@yori-temp, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        yori-temp-2: Could not introduce github.com/gruntwork-io/terratest@yori-temp-2, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        yori-temp-72: Could not introduce github.com/gruntwork-io/terratest@yori-temp-72, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.
        yori-temp-75: Could not introduce github.com/gruntwork-io/terratest@yori-temp-75, as it is not allowed by constraint yori-fix-more-dep-issues from project k8stests.

**Comment by yorinasub17** [comment] 2019-08-05 14:59
Can you share your entire `Gopkg.toml` file? I'll try to reproduce and figure out your issues. Something is still pulling in `k8s.io/api` as a transitive dependency...

**Comment by KyleMartin901** [comment] 2019-08-09 00:05
I am also having this problem using go modules. It was working perfectly using just the Terraform module but once I added K8s it fails to download the dependancies

```go
package test

import (
	"testing"

	"github.com/gruntwork-io/terratest/modules/k8s"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)
```

```bash
export GO111MODULE=on
go mod init example.com/test
go test > go-mod.log 2>&1
```

[go-mod.log](https://github.com/gruntwork-io/terratest/files/3484043/go-mod.log)

I tried your patch but it still failed

```bash
go get -v github.com/gruntwork-io/terratest/modules/k8s@98a6957 > go-mod-98a6957.log 2>&1
```

[go-mod-98a6957.log](https://github.com/gruntwork-io/terratest/files/3484116/go-mod-98a6957.log)

**Comment by yorinasub17** [comment] 2019-08-09 00:07
FYI we don't support go modules yet. See and track https://github.com/gruntwork-io/terratest/issues/345

**Comment by yorinasub17** [comment] 2019-08-09 00:08
And https://github.com/gruntwork-io/terratest/pull/264 for the relevant discussion on why we are waiting for Go 1.13.

**Comment by KyleMartin901** [comment] 2019-08-09 00:43
Thanks heaps sorry I was struggling getting dep to work as it turns out my work network was blocking it 😔so I was finally was able to get dep setup and working correctly and all my k8s tests are now running correctly using v0.18.3. 

Sorry again and thanks for all your tolling.

```toml
[[constraint]]
  name = "github.com/gruntwork-io/terratest"
  version = "0.18.3"
```

**Comment by yorinasub17** [comment] 2019-08-09 00:51
Understandable. `dep` has been difficult to work with the Kubernetes packages since they don't officially support it so I have had to hard code the transitive dependencies. Once we are ready to migrate to go modules, all of this should be significantly easier.

**Comment by git4raj** [comment] 2019-09-25 19:56
I'm having the same issue. However,I'm not even importing k8s modules.
All I'm doing is 
go get  github.com/gruntwork-io/terratest/modules/terraform
go get  github.com/gruntwork-io/terratest/modules/test-structure

It is throwing the error 
package k8s.io/kubernetes/pkg/kubectl/generate: cannot find package "k8s.io/kubernetes/pkg/kubectl/generate"

**Comment by yorinasub17** [comment] 2019-09-25 20:25
This is because the terratest code is referencing the kubernetes libraries and go is not able to independently compile the individual packages (it tries to compile the whole repo). Right now you have to use `dep` if you want to use terratest.

**Comment by yorinasub17** [comment] 2019-09-30 20:09
We are no longer dependent on kubernetes core for `tunnel.go`. This should no longer be a problem starting with [v0.19.2](https://github.com/gruntwork-io/terratest/releases/tag/v0.19.2)

**Closed by yorinasub17** 2019-09-30 20:09 UTC
Labels: bug
